project:
  type: website
  output-dir: docs

website:
  title: "Image Segmentation for Microscopy"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: setup.html
        text: "Setup"
      - text: "Sessions"
        menu:
        - text: "Microscopy Context"
          href: notebooks/01_microscopy.html
        - text: "Labeling and Annotation"
          href: notebooks/02_labeling.html
        - text: "Segmentation with Avizo"
          href: notebooks/03_avizo.html
        - text: "Segmentation with YOLO"
          href: notebooks/03b_yolo.html
        - text: "Tools"
          href: notebooks/04_tools.html



  cookie-consent:
    type: express
    style: simple
    palette: light
    policy-url: https://www.sydney.edu.au/privacy-statement.html
  google-analytics: "G-TNWWV3HK57"

  page-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

format:
  html:
   toc: true
   css: [styles.scss]
   quarto-margin-sidebar:
     max-width: 1000px
   theme:
      light: flatly
      dark: darkly

   code-link: true
   code-fold: false
