---
title: "Image Segmentation at Sydney Microscopy and Microanalysis"
output:
  html_document:
    toc: false
    toc_float: false
---


This is a training course aimed at users of the Sydney Microscopy and Microanalysis Core Research Facility at the University of Sydney who want to annotate their images using AI-assisted tools.

## Watch the Recording

This was delivered as an interactive workshop at Sydney. If you find yourself here in the future feel free to watch the recording:

TODO

## Contributors

* [Seb](https://www.sydney.edu.au/research/facilities/sydney-informatics-hub/our-staff.html) SIH
* [Nathaniel Butterworth](https://www.sydney.edu.au/research/facilities/sydney-informatics-hub/our-staff.html) SIH
* [Chad Moore](https://www.sydney.edu.au/research/facilities/sydney-informatics-hub/our-staff.html) SMM
* [Andre Venne](https://www.sydney.edu.au/research/facilities/sydney-informatics-hub/our-staff.html) SMM


## Course pre-requisites and setup requirements

No previous programming experience is required, this training course will introduce you to fundamentals of the various tools (unix, Python) as required. Training will be delivered online, so you will need access to a modern computer with a stable internet connection. Participants will require the Sydney VPN and a terminal client (as per the [Setup Instructions](./setup.html) provided).


## Venue

Online via Zoom, a link will be shared with registered participants.

#### Zoom etiquette and how we interact

Sessions will be recorded and added to this page. Please interrupt whenever you want! Ideally, have your camera on and interact as much as possible. There will be someone monitoring the chat-window for any questions you would like to post there.  Extending for a three-hour duration, our Zoom session incorporates regular breaks and a blend of demonstrative and hands-on material.


## Code of Conduct

As a University of Sydney course, we also want to make sure peopele are aware of our code of conduct.
Feel free to move this to an about page as needed.

Example standard Code of Conduct statement:

We expect all attendees of our training to follow our code of conduct, including bullying, harassment and discrimination prevention policies.

In order to foster a positive and professional learning environment we encourage the following kinds of behaviours at all our events and on our platforms:

* Use welcoming and inclusive language
* Be respectful of different viewpoints and experiences
* Gracefully accept constructive criticism
* Focus on what is best for the community
* Show courtesy and respect towards other community members

Our full CoC, with incident reporting guidelines, is available [Here](https://sydney-informatics-hub.github.io/codeofconduct/).



## Schedule

|  |  |
| --- | :--- |
| **In-depth** |
|   | [AI Image Segmentaion Microscopy Context](notebooks/01_microscopy.qmd) |
|   | [AI Assisted Labeling and Annotation](notebooks/02_labeling.qmd) |
|   | [Avizo Image Segmentation Workflow](notebooks/03_avizo.qmd) |
|   | [Yolo Image Segmentation Workflow](notebooks/03b_yolo.qmd) |
|   | [Conversion and Data Analysis Tools](notebooks/04_tools.qmd) |


## Setup Instructions

Please attempt to complete the [Setup Instructions](./setup.html) **before the course**. We will run through this in the course too.
